# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    my_provider:
        class: MyUserBundle\Security\MyUserProvider
        arguments: ['@fos_user.user_manager']

    authentication_handler:
        class: MyUserBundle\Security\FailureHandler
        arguments: ['@router', '@fos_user.user_manager' ]

    my_password_encoder:
        class: MyUserBundle\Security\MyPasswordEncoder