services:

    cdg_registration_confirm_listener:
        class: MyUserBundle\EventListener\RegistrationConfirmListener
        arguments: ['@router', '@session']
        tags:
            - { name: kernel.event_subscriber }

    auth_success_handler:
        class: MyUserBundle\Security\LoginSuccessHandler
        arguments: ['@router', '@param_user_repository', '@session']

    auth_failure_handler:
        class: MyUserBundle\Security\FailureHandler
        arguments: ['@router', '@fos_user.user_manager', '@session']

    my_password_encoder:
        class: MyUserBundle\Security\MyPasswordEncoder

    #J'ai mis le meme nom que le listener de fosuserpourl'override mais faire attention car ca va supprimer
    #le comportement pour tous les messages flash. A voir si c'est ce que je veux
    fos_user.listener.flash:
        class: MyUserBundle\EventListener\FlashListener
        arguments: ['@session', '@translator']
        tags:
            - { name: kernel.event_subscriber }