home:
    path:     /
    defaults: { _controller: CoursdeGratteBundle:Main:index }

single:
    path:     /tuto/{slug}-{id}
    defaults:  { _controller: CoursdeGratteBundle:Tuto:show }
    requirements:
        slug: "[a-z0-9\/-]+"
        id: \d+

#Renvoyer l'email de confirmation
resend:
    path: /user/resend/{email}
    defaults: {_controller: MyUserBundle:User:resend }

#Requete Ajax
ajax_main:
    path:     /ajax
    defaults: { _controller: CoursdeGratteBundle:Ajax:ajax }

ajax_prof:
    path:     /prof
    defaults: { _controller: CoursdeGratteBundle:Ajax:ajaxProf }

ajax_style:
    path:     /style
    defaults: { _controller: CoursdeGratteBundle:Ajax:ajaxStyle }

ajax_typeahead:
    path:     /typeahead
    defaults: { _controller: CoursdeGratteBundle:Ajax:typeahead }

#Fin des requetes ajax

move_users:
    path: /moveuser
    defaults: { _controller: CoursdeGratteBundle:Main:moveUserFromOldToNewDatabase }