main:
    path:     /
    defaults: { _controller: CoursdeGratteBundle:Main:index }

test:
    path:     /test
    defaults: { _controller: CoursdeGratteBundle:Main:test }
ajax_main:
    path:     /ajax
    defaults: { _controller: CoursdeGratteBundle:Ajax:ajax }

ajax_prof:
    path:     /prof
    defaults: { _controller: CoursdeGratteBundle:Ajax:ajaxProf }

ajax_style:
    path:     /style
    defaults: { _controller: CoursdeGratteBundle:Ajax:ajaxStyle }