services:

    param_user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - CoursdeGratteBundle\Entity\Paramuser
